<?php

namespace GestionFaenaBundle\Repository;

/**
 * FaenaDiariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaenaDiariaRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllFaenas() { 
	    return $this->createQueryBuilder('f')
			        ->addOrderBy('f.fechaFaena', 'DESC')
			        ->getQuery()
			        ->getResult(); 
	} 
}
