<?php

namespace GestionFaenaBundle\Repository;

/**
 * GrupoMovimientosAutomaticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoMovimientosAutomaticoRepository extends \Doctrine\ORM\EntityRepository
{
}
