<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ComprobanteVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
