<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ConceptoMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
