<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ItemCargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCargaRepository extends \Doctrine\ORM\EntityRepository
{

	public function itemsAImprimir(\GestionFaenaBundle\Entity\faena\ComprobanteVenta $comprobante, $oficial) 
	{ 
	    $q = $this->createQueryBuilder('it')
	    		   ->join('it.articulo', 'art')
	    		   ->join('art.categoria', 'cat')
	    		   ->join('it.tipoVenta', 'tpo')
	    		   ->where('it.comprobante = :comprobante');
	    if ($oficial)
	    {
	    	$q->andWhere('tpo.oficial = :oficial')
	    	  ->setParameter('oficial', $oficial);
	    }
	    return $q->setParameter('comprobante', $comprobante)
		          ->orderBy('art.grupo', 'ASC')
		          ->addOrderBy('cat.orden')
		          ->addOrderBy('art.nombre')
		          ->getQuery()
		          ->getResult(); 
	} 
}
