<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * OrdenCargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenCargaRepository extends \Doctrine\ORM\EntityRepository
{

    //Devuelve una orden de carga -de existir- que tenga como alguno de los destinatarios la entidad recibida, para la faena recibida como parametro
    public function findOrdenCargaEntidad(\GestionFaenaBundle\Entity\gestionBD\EntidadExterna $entidad, 
    									  \GestionFaenaBundle\Entity\FaenaDiaria $faena)
    {
        return $this->getEntityManager()
            		->createQuery('SELECT o
	                               FROM GestionFaenaBundle:faena\OrdenCarga o 
	                               WHERE  o.eliminado = :eliminado AND o.faenaDiaria =:faena AND ((:entidad MEMBER OF o.entidades) OR (o.rubro = :rubro))')
            		->setParameter('faena', $faena)
                	->setParameter('eliminado', false)
                	->setParameter('entidad', $entidad)
                	->setParameter('rubro', $entidad->getRubro())
            		->getOneOrNullResult();
    }
}
