<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ProcesoFaenaDiariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoFaenaDiariaRepository extends \Doctrine\ORM\EntityRepository
{
}
