<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ValorNumericoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorNumericoRepository extends \Doctrine\ORM\EntityRepository
{
}
