<?php

namespace GestionSigcerBundle\Repository;

/**
 * DetalleSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
