<?php

namespace GestionSigcerBundle\Repository;

/**
 * GrupoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllGrupos() { 
	    return $this->createQueryBuilder('f')
			        ->addOrderBy('f.fecha', 'DESC')
			        ->getQuery()
			        ->getResult(); 
	} 
}
