<?php

namespace GestionSigcerBundle\Repository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSolicitudes(\GestionSigcerBundle\Entity\GrupoSolicitud $grupo,
									\GestionSigcerBundle\Entity\opciones\Region $region) 
	{ 
	    return $this->createQueryBuilder('s')
	    			->join('s.zona', 'z')
	    			->where('z.region = :region AND s.grupo = :grupo')
	    			->setParameter('region', $region)
	    			->setParameter('grupo', $grupo)
			        ->addOrderBy('z.codigo')
			        ->getQuery()
			        ->getResult(); 
	} 
}
