<?php

namespace GestionSigcerBundle\Repository;

/**
 * TropaSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TropaSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
