<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{

	public function getListaArticulos() 
	{ 
        return $this->getEntityManager()
            		->createQuery('SELECT a
            					   FROM GestionFaenaBundle:gestionBD\Articulo a 
            					   JOIN a.categoria c
                                   JOIN a.subcategoria s
            					   WHERE a.eliminado = :eliminado
            					   ORDER BY c.orden, s.orden, a.codigoInterno')
            		->setParameter('eliminado', false)
            		->getResult();
	} 
}
