<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{

	public function getListaArticulos() 
	{ 
        return $this->getEntityManager()
            		->createQuery('SELECT a
            					   FROM GestionFaenaBundle:gestionBD\Articulo a 
            					   LEFT JOIN a.categoria c
                                   LEFT JOIN a.subcategoria s
            					   WHERE a.eliminado = :eliminado
            					   ORDER BY c.orden, s.orden, a.orden, a.id')
            		->setParameter('eliminado', false)
            		->getResult();
	} 

    public function getListaArticulosConCategoria() 
    { 
        return $this->getEntityManager()
                    ->createQuery('SELECT a
                                   FROM GestionFaenaBundle:gestionBD\Articulo a 
                                   JOIN a.categoria c
                                   JOIN a.subcategoria s
                                   WHERE a.eliminado = :eliminado
                                   ORDER BY c.orden, s.orden, a.orden, a.id')
                    ->setParameter('eliminado', false)
                    ->getResult();
    } 
}
