<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * EntidadExternaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadExternaRepository extends \Doctrine\ORM\EntityRepository
{
}
