<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * TransportistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportistaRepository extends \Doctrine\ORM\EntityRepository
{
}
